### ISSUE TITLE
Example project does not work

### ISSUE THREAD

**Issue by hughanderson4** [Grafikart/ts-vue-loader#1]
Example project included in this repo does not work.  It does not even reference ts-vue-loader
```
ERROR in ./src/main.ts
Module build failed: Error: Cannot find module 'vue-template-compiler'
````
I do not understand how to use Example project.
Am I supposed to use a combination of the config in `/package.json` and `/example/package.json` ??

2nd question: is it possible to use .Vue files with both `<template>` and Typescript section?  Can you please provide an example how to do that?  This would allow to reuse a lot of Vue examples, but still have Typescript type checking.

**Comment by Grafikart** [comment]
I'm fixing the issue and will provide an example for your second question

**Comment by Grafikart** [comment]
Fixed https://github.com/Grafikart/ts-vue-loader/tree/master/example

**Comment by hughanderson4** [comment]
oh hey, that make a lot more sense now.  thank u!

**Comment by Grafikart** [comment]
@s-KaiNet If you use `.vue` files you can set template using the `<template>` tags and the vue-loader will handle things. This loader is inteded for people that want to create vue component without using the `.vue` extension.

**Comment by s-KaiNet** [comment]
oh.. now I see, thank you! Then probably I didn't setup everything correctly because hmr doesn't work for me when using SFC and TypeScript.  Anyway, thank you for a quick answer, I will try to find an issue with my setup.

**Comment by s-KaiNet** [comment]
I'll leave it here for anybody who has similar issues.   
It appeared that ts-loader doesn't support hot module replacement, however, you can enable it by setting `transpileOnly: true`. In that case, we lose type checking, to enable type checking you should install [fork-ts-checker-webpack-plugin](https://github.com/Realytics/fork-ts-checker-webpack-plugin) for type checking and provide additional config:  
```js
new ForkTsCheckerWebpackPlugin({
      tslint: true,
      vue: true
    }),
```  
I've created sample starter for my case, maybe that's will be usefull for somebody - [vue-ts-sfc-webpack-hmr](https://github.com/s-KaiNet/vue-ts-sfc-webpack-hmr)
